package main

func main() {
	HelloWorld()
	Slice()
	CopySlice()
	SliceAppend()
	SliceMake()
	MapTypeData()
	SwitchCase()
	ForLoop()
	ForLoopWithStatement()
	ForRange()
	Break()
	Continue()
	ContohFunction()
	ContohFunctionWithParam("Joko")
	ContohFunctionWithReturn()
	ContohVariadicFunction()
	ContohVariadicFunctionSlice()
	ContohFunctionAsParam()
	RecursiveFunction()
	ContohDefer()
	ContohPanic()
	CreateDataFromStruct()
	RunStructMethod()
	ContohImplementInterface()
	PenggunaanInterfaceKosong()
	ContohErrorInterface()
	ContohPengguaanPointer()
}
